# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
  
  runs-on: windows-latest
  
    strategy:
      matrix:
        node-version: 14.16
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
- uses: actions/checkout@v2
- name: Use Node.js
  uses: actions/setup-node@v1
  with:
    node-version: '14.x'
- name: Install dependencies
  run: npm ci
